apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: phonebook-service
  namespace: phonebook-v1
spec:
  host: phonebook-service
  subsets:
  - name: v1
    labels:
      version: '1.0'
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN       
  - name: v2
    labels:
      version: '2.0'
