apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      number: 8080
      name: http-web
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingressgateway
spec:
  hosts:
  - '*'
  gateways:
  - ingressgateway
  http:
  - fault:
      abort:
        httpStatus: 404
        percentage:
          value: 10
    route:
    - destination:
        host: phonebook-service.phonebook-v1.svc.cluster.local
      weight: 50
    - destination:
         host: phonebook-service-v2.phonebook-v1.svc.dr-imports.local
      weight: 50
