apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: product
    descriptors:
      - key: PATH
        rate_limit:
          unit: second
          requests_per_unit: 100
